package objc

const (
	EncId          = "@"
	EncClass       = "#"
	EncSelector    = ":"
	EncChar        = "c"
	EncUChar       = "C"
	EncShort       = "s"
	EncUShort      = "S"
	EncInt         = "i"
	EncUInt        = "I"
	EncLong        = "l"
	EncULong       = "L"
	EncLongLong    = "q"
	EncULongLong   = "Q"
	EncFloat       = "f"
	EncDouble      = "d"
	EncDFLD        = "b"
	EncBool        = "B"
	EncVoid        = "v"
	EncUndef       = "?"
	EncPtr         = "^"
	EncCharPtr     = "*"
	EncAtom        = "%"
	EncArrayBegin  = "["
	EncArrayEnd    = "]"
	EncUnionBegin  = "("
	EncUnionEnd    = ")"
	EncStructBegin = "{"
	EncStructEnd   = "}"
	EncVector      = "!"
	EncConst       = "r"
)
