include $(GOROOT)/src/Make.inc

TARG=github.com/mkrautz/go-objc/Foundation

CGOFILES=init.go
GOFILES=\
	doc.go\
	NSAutoreleasePool.go\
	NSRunLoop.go\
	NSThread.go\
	NSString.go\
	NSRect.go\
	NSSize.go\
	NSPoint.go\
	NSUInteger.go\

include $(GOROOT)/src/Make.pkg
